variable "aws_api_gateway_method_http_method" {}
variable "aws_api_gateway_method_authorization" {}
variable "aws_api_gateway_rest_api" {}
variable "aws_api_gateway_resource_id" {}
variable "aws_api_gateway_resource_path" {}
variable "aws_lambda_function_arn" {}
variable "aws_lambda_function_name" {}
variable "aws_region" {}
variable "aws_account_id" {}
variable "environment_name" {}